name = "Hyde-Like"
license = "MIT"
licenselink = "https://github.com/polybuildr/hyde-like/blob/master/LICENSE"
description = "Looks like @mdo's hyde, but with some tweaks to the style and code."
tags = ["blog", "minimal", "responsive"]
features = []
min_version = "0.21"

[author]
  name = "Vivek Ghaisas (polybuildr)"
  homepage = "https://vghaisas.com"

# The original, non-Hugo theme
[original]
  name = "mdo"
  # Details from original theme's config
  homepage = "https://twitter.com/mdo"
  repo = "https://github.com/poole/hyde"
